# Generated by Django 5.0.1 on 2024-01-11 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-published_at'], name='blog_post_categor_cb6e5f_idx'),
        ),
    ]
