# Generated by Django 5.0.1 on 2024-01-13 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_blog_post_categor_cb6e5f_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_at',), 'verbose_name_plural': 'Посты'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['published_at'], name='blog_commen_publish_5eb8c8_idx')],
            },
        ),
    ]
